# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: &name KockaAdmiralac
email: admin@kocka.tech
description: "Personal site of KockaAdmiralac."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kocka.tech" # the base hostname & protocol for your site, e.g. http://example.com
repository: KockaAdmiralac/kockaadmiralac.github.io
timezone: Europe/Belgrade

# Customization
head_scripts:
footer_scripts:
after_footer_scripts:
teaser:
logo:
og_image:

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dark
plugins:
  - jekyll-include-cache

# SEO
google_site_verification: hGFr2GZy7GOlxAnzR83PvaMGM_jxy6gg5pktzZ9hL2M
bing_site_verification:
yandex_site_verification: be0d2ef7fca223a2
naver_site_verification:

# Social
twitter:
  username: KockaAdmiralac
social:
  links:
    - "https://twitter.com/KockaAdmiralac"
    - "https://github.com/KockaAdmiralac"
    - "https://dev.fandom.com/wiki/User:KockaAdmiralac"
    - "https://help.gamepedia.com/UserProfile:KockaAdmiralac"
    - "https://twitch.tv/kockaadmiralac"
    - "https://stackoverflow.com/users/4335370/kockaadmiralac"

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-147950049-1"
    anonymize_ip: true

# Author
author:
  name: "Luka Simić"
  avatar:
  bio: "Јуче је данас било сутра."
  location: "Belgrade, Serbia"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kocka.tech"
    - label: "KockaAdmiralac#9306"
      icon: "fab fa-fw fa-discord"
      url: "https://discordapp.com/users/148231501413089280"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KockaAdmiralac"
    - label: "E-mail"
      icon: "fa fa-envelope"
      url: "mailto:luka@kocka.tech"
    - label: "Fandom"
      # https://github.com/FortAwesome/Font-Awesome/issues/12585
      icon: "fa fa-heart"
      url: "https://dev.fandom.com/wiki/User:KockaAdmiralac"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/KockaAdmiralac"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://twitch.tv/kockaadmiralac"
    - label: "Gamepedia"
      icon: "fas fa-gamepad"
      url: "https://help.gamepedia.com/UserProfile:KockaAdmiralac"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/4335370/kockaadmiralac"

include:
  - _pages
exclude:
  - _config.yml
  - .asset-cache
  - .bundle
  - .gitignore
  - .jekyll-assets-cache
  - .jekyll-metadata
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - cacert.pem
  - CNAME
  - Gemfile
  - Gemfile.lock
  - serve.sh
  - LICENSE
  - README.md
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "md"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# See https://pages.github.com/versions/
whitelist:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# HTML compression
compress_html:
  clippings: all

